version: "3"
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  code-chrome:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - chrome
      - firefox
    command : mvn clean test -DsuiteXmlFile="src/test/resources/testData/testng.xml" -Dbrowser="chrome"
    volumes:
      - ./target/test-output:/usr/share/maven/sample/test-output/
  code-firefox:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - chrome
      - firefox
    command : mvn clean test -DsuiteXmlFile="src/test/resources/testData/testng.xml" -Dbrowser="firefox"
    volumes: 
      - ./target/:/usr/share/maven/target/
      - ./test-output/:/usr/share/maven/sample/test-output/
